services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./web-config/nginx:/etc/nginx/
      - ./web-config/nginx/auth:/etc/nginx/auth
      - certs:/etc/ssl/certs
      - /home/rawcsav/AIUtilsFlask/app:/newutil/app
      - /home/rawcsav/RawcOn/app:/rawcon/app
    networks:
      - appnet
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  cloudflared:
    image: cloudflare/cloudflared:latest
    dns:
      - 100.94.221.96 # Google's DNS as backup
      - 1.1.1.1  # Cloudflare's DNS
    command: tunnel --no-autoupdate run ${CLOUDFLARED_TUNNEL_ID}
    volumes:
      - ./web-config/cloudflared:/etc/cloudflared
    depends_on:
      - nginx
    restart: unless-stopped
    networks:
      - appnet

volumes:
  certs:
    driver: local
    driver_opts:
      type: none
      device: /home/rawcsav/DockSec/web-config/certs/
      o: bind

networks:
  appnet:
    external: true
