version: '3.8'
services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./web-config/nginx:/etc/nginx/
      - certs:/etc/ssl/certs
      - /home/rawcsav/AIUtilsFlask/app:/newutil/app
      - /home/rawcsav/SpotifyFlask/app:/rawcon/app
    networks:
      - appnet
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run ${CLOUDFLARED_TUNNEL_ID}
    volumes:
      - ./web-config/cloudflared:/etc/cloudflared
    depends_on:
      - nginx
    restart: unless-stopped
    networks:
      - appnet

  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_PASS}
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    volumes:
      - prometheus_data:/prometheus
    command:
      - --web.enable-admin-api
      - --web.enable-lifecycle
      - --config.file=/etc/prometheus/prometheus.yml
    restart: unless-stopped

volumes:
  certs:
    driver: local
    driver_opts:
      type: none
      device: /home/rawcsav/DockSec/web-config/certs/
      o: bind
  grafana_data:
  prometheus_data:

networks:
  appnet:
    external: true
