version: '3'
services:
  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_PASS}
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - appnet

  prometheus:
    image: prom/prometheus
    volumes:
      - prometheus_data:/prometheus
    command:
      - --web.enable-admin-api
      - --web.enable-lifecycle
      - --config.file=/etc/prometheus/prometheus.yml
    restart: unless-stopped
    networks:
      - appnet


networks:
  appnet:
    external: true
