version: '3.8'
services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./web-config/nginx:/etc/nginx/
      - certs:/etc/ssl/certs
      - /home/rawcsav/AIUtilsFlask/app:/newutil/app
      - /home/rawcsav/SpotifyFlask/app:/rawcon/app
    ports:
      - "80:80"
      - "443:443"
    networks:
      - appnet
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run ${CLOUDFLARED_TUNNEL_ID}
    volumes:
      - ./web-config/cloudflared:/etc/cloudflared
    depends_on:
      - nginx
    restart: unless-stopped
    networks:
      - appnet

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "8053:53/tcp"
      - "8053:53/udp"
      - "8067:67/udp"
      - "8080:80/tcp"
    environment:
      TZ: 'America/New_York'
      WEBPASSWORD: ${WEBPASSWORD}
      SERVERIP: ${SERVERIP}
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    dns:
      - 127.0.0.1
      - 1.1.1.1
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/admin/"]
      interval: 1m
      timeout: 10s
      retries: 3
    networks:
      - appnet


volumes:
  certs:
    driver: local
    driver_opts:
      type: none
      device: /home/rawcsav/DockSec/web-config/certs/
      o: bind

networks:
  appnet:
    external: true
