version: "3.8"
services:
  dashy:
    image: lissy93/dashy
    container_name: Dashy
    volumes:
      - ../web-config/monitor/my-config.yml:/app/user-data/conf.yml
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
        - appnet


networks:
    internal:
      driver: "bridge"
    appnet:
      external: true